name: set_solver
description: A library to find sets in the Set card/board game
version: 0.0.1
repository: https://github.com/mharbol/set_solver/

environment:
  sdk: ^3.1.0

# Add regular dependencies here.
dependencies:
  # path: ^1.8.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
